name: Run tests

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  run-sh-tests:
    name: Run shell tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build docker image
        run: cd sh && ./../docker-build.sh

      - name: Run tests
        run: ./run-tests.sh

  run-cpp-tests:
    name: Run c++ tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build docker image
        run: cd cpp && ./../docker-build.sh

#      - name: Run tests
#        run: ./run-tests.sh

  run-python3-tests:
    name: Run python 3 tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build docker image
        run: cd python3 && ./../docker-build.sh

#      - name: Run tests
#        run: ./run-tests.sh
